version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .dockerfile
    image: auth-backend
    container_name: auth-backend
    restart: unless-stopped
    ports:
      - "8091:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public